import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

const resources = {
  en: {
    translation: {
      // Navigation
      home: "Home",
      services: "Services",
      about: "About",
      contact: "Contact",
      admin: "Admin",
      
      // Hero Section
      heroTitle: "Bank of India",
      heroSubtitle: "Business Correspondent Point",
      heroDescription: "Your trusted banking partner providing comprehensive financial services",
      getStarted: "Get Started",
      learnMore: "Learn More",
      
      // Services
      servicesTitle: "Our Services",
      servicesSubtitle: "Comprehensive Banking & Digital Services",
      
      // Features
      featuresTitle: "Features",
      featuresSubtitle: "वैशिष्ट्ये",
      
      // Banking hours
      bankingHours: "Banking Hours",
      morningHours: "Morning: 10 AM - 1 PM",
      eveningHours: "Evening: 6 PM - 9 PM",
      
      // Services
      panCard: "PAN Card Services",
      panCardDesc: "Apply for new PAN card or update existing details",
      xeroxPrinting: "Xerox & Printing",
      xeroxPrintingDesc: "Document xerox, printing, and scanning services",
      electricityBill: "Electricity Bill Payment",
      electricityBillDesc: "Pay your electricity bills online quickly and securely",
      eServices: "E-Services Forms",
      eServicesDesc: "Fill various government e-service forms online",
      bankingServices: "Banking Services",
      bankingServicesDesc: "Complete banking solutions for all your needs",
      
      // About
      aboutTitle: "About BC Point",
      aboutDescription: "Bank of India Business Correspondent Point provides essential banking services to rural and semi-urban areas. We bridge the gap between formal banking and underserved communities.",
      
      // Contact
      contactTitle: "Contact Us",
      contactDescription: "Get in touch with us for any queries or assistance",
      
      // Footer
      footerDesc: "Bank of India BC Point - Your trusted financial partner",
      quickLinks: "Quick Links",
      followUs: "Follow Us",
      
      // Daily Content
      dailyQuote: "Daily Quote",
      dailyTip: "Daily Tip",
      dailyFact: "Daily Fact",
      
      // AI Assistant
      aiAssistant: "AI Assistant",
      askQuestion: "Ask a question...",
      send: "Send",
      
      // Common
      loading: "Loading...",
      error: "Error",
      success: "Success",
      close: "Close",
      submit: "Submit",
      cancel: "Cancel",
      
      // Anti-copy messages
      copyDisabled: "Content copying is disabled on this website",
      screenshotDisabled: "Screenshot functionality is disabled for security reasons",
      
      // Terms & Privacy
      termsConditions: "Terms & Conditions",
      privacyPolicy: "Privacy Policy",
      autoGenerated: "Auto-generated legal document",
      
      // Language
      language: "Language",
      english: "English",
      hindi: "हिंदी",
      marathi: "मराठी"
    }
  },
  hi: {
    translation: {
      // Navigation
      home: "होम",
      services: "सेवाएं",
      about: "के बारे में",
      contact: "संपर्क",
      admin: "प्रशासक",
      
      // Hero Section
      heroTitle: "बैंक ऑफ इंडिया",
      heroSubtitle: "बिजनेस कॉरेस्पॉन्डेंट पॉइंट",
      heroDescription: "आपका भरोसेमंद बैंकिंग पार्टनर जो व्यापक वित्तीय सेवाएं प्रदान करता है",
      getStarted: "शुरू करें",
      learnMore: "और जानें",
      
      // Services
      servicesTitle: "हमारी सेवाएं",
      servicesSubtitle: "व्यापक बैंकिंग और डिजिटल सेवाएं",
      
      // Features
      featuresTitle: "विशेषताएं",
      featuresSubtitle: "वैशिष्ट्ये",
      
      // Banking hours
      bankingHours: "बैंकिंग समय",
      morningHours: "सुबह: 10 बजे - 1 बजे",
      eveningHours: "शाम: 6 बजे - 9 बजे",
      
      // Services
      panCard: "पैन कार्ड सेवाएं",
      panCardDesc: "नया पैन कार्ड बनाने या मौजूदा विवरण अपडेट करने के लिए आवेदन करें",
      xeroxPrinting: "जेरॉक्स और प्रिंटिंग",
      xeroxPrintingDesc: "दस्तावेज़ जेरॉक्स, प्रिंटिंग और स्कैनिंग सेवाएं",
      electricityBill: "बिजली बिल भुगतान",
      electricityBillDesc: "अपने बिजली बिल का भुगतान ऑनलाइन तुरंत और सुरक्षित रूप से करें",
      eServices: "ई-सेवा फॉर्म",
      eServicesDesc: "विभिन्न सरकारी ई-सेवा फॉर्म ऑनलाइन भरें",
      bankingServices: "बैंकिंग सेवाएं",
      bankingServicesDesc: "आपकी सभी आवश्यकताओं के लिए संपूर्ण बैंकिंग समाधान",
      
      // About
      aboutTitle: "बीसी पॉइंट के बारे में",
      aboutDescription: "बैंक ऑफ इंडिया बिजनेस कॉरेस्पॉन्डेंट पॉइंट ग्रामीण और अर्ध-शहरी क्षेत्रों में आवश्यक बैंकिंग सेवाएं प्रदान करता है। हम औपचारिक बैंकिंग और अविकसित समुदायों के बीच की खाई को पाटते हैं।",
      
      // Contact
      contactTitle: "संपर्क करें",
      contactDescription: "किसी भी प्रश्न या सहायता के लिए हमसे संपर्क करें",
      
      // Footer
      footerDesc: "बैंक ऑफ इंडिया बीसी पॉइंट - आपका भरोसेमंद वित्तीय पार्टनर",
      quickLinks: "त्वरित लिंक",
      followUs: "हमें फॉलो करें",
      
      // Daily Content
      dailyQuote: "दैनिक उद्धरण",
      dailyTip: "दैनिक सुझाव",
      dailyFact: "दैनिक तथ्य",
      
      // AI Assistant
      aiAssistant: "एआई सहायक",
      askQuestion: "एक प्रश्न पूछें...",
      send: "भेजें",
      
      // Common
      loading: "लोड हो रहा है...",
      error: "त्रुटि",
      success: "सफलता",
      close: "बंद करें",
      submit: "जमा करें",
      cancel: "रद्द करें",
      
      // Anti-copy messages
      copyDisabled: "इस वेबसाइट पर कंटेंट कॉपी करना अक्षम है",
      screenshotDisabled: "सुरक्षा कारणों से स्क्रीनशॉट कार्यक्षमता अक्षम है",
      
      // Terms & Privacy
      termsConditions: "नियम और शर्तें",
      privacyPolicy: "गोपनीयता नीति",
      autoGenerated: "स्वचालित रूप से तैयार कानूनी दस्तावेज़",
      
      // Language
      language: "भाषा",
      english: "English",
      hindi: "हिंदी",
      marathi: "मराठी"
    }
  },
  mr: {
    translation: {
      // Navigation
      home: "होम",
      services: "सेवा",
      about: "बद्दल",
      contact: "संपर्क",
      admin: "प्रशासक",
      
      // Hero Section
      heroTitle: "बँक ऑफ इंडिया",
      heroSubtitle: "बिझनेस कॉरेस्पॉन्डेंट पॉइंट",
      heroDescription: "तुमचा विश्वसनीय बँकिंग पार्टनर जो व्यापक आर्थिक सेवा पुरवतो",
      getStarted: "सुरुवात करा",
      learnMore: "अधिक जाणा",
      
      // Services
      servicesTitle: "आमच्या सेवा",
      servicesSubtitle: "व्यापक बँकिंग आणि डिजिटल सेवा",
      
      // Features
      featuresTitle: "वैशिष्ट्ये",
      featuresSubtitle: "वैशिष्ट्ये",
      
      // Banking hours
      bankingHours: "बँकिंग वेळ",
      morningHours: "सकाळ: 10 ते 1",
      eveningHours: "सायंकाळ: 6 ते 9",
      
      // Services
      panCard: "पॅन कार्ड सेवा",
      panCardDesc: "नवीन पॅन कार्ड बनवण्यासाठी किंवा विद्यमान तपशील अपडेट करण्यासाठी अर्ज करा",
      xeroxPrinting: "झेरॉक्स व प्रिंटिंग",
      xeroxPrintingDesc: "दस्तऐवज झेरॉक्स, प्रिंटिंग आणि स्कॅनिंग सेवा",
      electricityBill: "लाईट बिल भरणे",
      electricityBillDesc: "तुमचे वीज बिल ऑनलाइन झटपट आणि सुरक्षितपणे भरा",
      eServices: "ई-सेवा फॉर्म",
      eServicesDesc: "विविध सरकारी ई-सेवा फॉर्म ऑनलाइन भरा",
      bankingServices: "बँकिंग सेवा",
      bankingServicesDesc: "तुमच्या सर्व गरजांसाठी संपूर्ण बँकिंग समाधान",
      
      // About
      aboutTitle: "बीसी पॉइंट बद्दल",
      aboutDescription: "बँक ऑफ इंडिया बिझनेस कॉरेस्पॉन्डेंट पॉइंट ग्रामीण आणि अर्ध-शहरी भागात आवश्यक बँकिंग सेवा पुरवतो. आम्ही औपचारिक बँकिंग आणि अविकसित समुदायांमधील अंतर कमी करतो.",
      
      // Contact
      contactTitle: "संपर्क साधा",
      contactDescription: "कोणत्याही प्रश्न किंवा सहाय्यासाठी आमच्याशी संपर्क साधा",
      
      // Footer
      footerDesc: "बँक ऑफ इंडिया बीसी पॉइंट - तुमचा विश्वसनीय आर्थिक पार्टनर",
      quickLinks: "द्रुत लिंक",
      followUs: "आम्हाला फॉलो करा",
      
      // Daily Content
      dailyQuote: "दैनिक उद्धरण",
      dailyTip: "दैनिक टिप",
      dailyFact: "दैनिक तथ्य",
      
      // AI Assistant
      aiAssistant: "एआय सहायक",
      askQuestion: "प्रश्न विचारा...",
      send: "पाठवा",
      
      // Common
      loading: "लोड होत आहे...",
      error: "त्रुटी",
      success: "यशस्वी",
      close: "बंद करा",
      submit: "सबमिट करा",
      cancel: "रद्द करा",
      
      // Anti-copy messages
      copyDisabled: "या वेबसाइटवर कंटेंट कॉपी करणे अक्षम आहे",
      screenshotDisabled: "सुरक्षा कारणांसाठी स्क्रीनशॉट कार्यक्षमता अक्षम आहे",
      
      // Terms & Privacy
      termsConditions: "नियम आणि अटी",
      privacyPolicy: "गोपनीयता धोरण",
      autoGenerated: "स्वयंचलित तयार केलेले कायदेशीर दस्तऐवज",
      
      // Language
      language: "भाषा",
      english: "English",
      hindi: "हिंदी",
      marathi: "मराठी"
    }
  }
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'en',
    detection: {
      order: ['localStorage', 'navigator', 'htmlTag', 'path', 'subdomain'],
      caches: ['localStorage']
    },
    interpolation: {
      escapeValue: false
    }
  });

export default i18n;